-- Seed data generated from src/data/recipes.ts (the frontend's mock dataset).

insert into public.recipes (id, title, emoji, minutes, servings, tags, steps) values
  ('scrambled-eggs', 'Creamy Scrambled Eggs', '🍳', 10, 2, array['breakfast', 'vegetarian', 'quick'],
   array['Whisk eggs with milk and a pinch of salt.', 'Melt butter in a pan over low heat.', 'Add eggs and stir gently until just set.', 'Top with chives and serve.']),
  ('pancakes', 'Fluffy Pancakes', '🥞', 25, 4, array['breakfast', 'vegetarian'],
   array['Mix flour, sugar and baking powder.', 'Whisk in milk, eggs and melted butter until just combined.', 'Cook ladlefuls on a hot greased pan until bubbles form, then flip.']),
  ('garlic-pasta', 'Garlic Butter Pasta', '🍝', 20, 2, array['dinner', 'vegetarian', 'quick'],
   array['Boil pasta in salted water until al dente; reserve a cup of water.', 'Sauté sliced garlic in butter until golden.', 'Toss pasta with garlic butter, parmesan and a splash of pasta water.']),
  ('chicken-stir-fry', 'Chicken Veggie Stir-Fry', '🥘', 25, 3, array['dinner', 'high-protein'],
   array['Cook rice according to package.', 'Slice chicken and stir-fry in a hot oiled pan until browned.', 'Add garlic, peppers and broccoli; cook 4–5 minutes.', 'Add soy sauce, toss, and serve over rice.']),
  ('tomato-soup', 'Roasted Tomato Soup', '🍅', 45, 4, array['lunch', 'vegan'],
   array['Roast halved tomatoes, onion and garlic with olive oil at 200°C for 30 min.', 'Blend with broth until smooth.', 'Simmer 5 minutes and season to taste.']),
  ('guacamole', 'Classic Guacamole', '🥑', 10, 4, array['snack', 'vegan', 'quick'],
   array['Mash avocados with lime juice and salt.', 'Fold in finely diced onion, tomato and cilantro.']),
  ('fried-rice', 'Egg Fried Rice', '🍚', 15, 2, array['dinner', 'quick', 'vegetarian'],
   array['Scramble eggs in a hot oiled wok, set aside.', 'Fry cold cooked rice until slightly crisp.', 'Add peas, soy sauce, eggs and green onion; toss to combine.']),
  ('banana-bread', 'Banana Bread', '🍌', 70, 8, array['baking', 'vegetarian'],
   array['Mash bananas and mix with melted butter, sugar and egg.', 'Stir in flour and baking soda until just combined.', 'Bake in a loaf pan at 175°C for 55–60 minutes.']);

insert into public.recipe_ingredients (recipe_id, position, name, amount, unit, optional) values
  ('scrambled-eggs', 0, 'egg', 4, 'pcs', false),
  ('scrambled-eggs', 1, 'butter', 1, 'tbsp', false),
  ('scrambled-eggs', 2, 'milk', 2, 'tbsp', false),
  ('scrambled-eggs', 3, 'chive', 1, 'tbsp', true),
  ('pancakes', 0, 'flour', 200, 'g', false),
  ('pancakes', 1, 'milk', 300, 'ml', false),
  ('pancakes', 2, 'egg', 2, 'pcs', false),
  ('pancakes', 3, 'sugar', 2, 'tbsp', false),
  ('pancakes', 4, 'butter', 2, 'tbsp', false),
  ('pancakes', 5, 'baking powder', 2, 'tsp', false),
  ('garlic-pasta', 0, 'pasta', 200, 'g', false),
  ('garlic-pasta', 1, 'garlic', 4, 'pcs', false),
  ('garlic-pasta', 2, 'butter', 3, 'tbsp', false),
  ('garlic-pasta', 3, 'parmesan', 40, 'g', false),
  ('garlic-pasta', 4, 'parsley', 1, 'tbsp', true),
  ('chicken-stir-fry', 0, 'chicken breast', 400, 'g', false),
  ('chicken-stir-fry', 1, 'bell pepper', 2, 'pcs', false),
  ('chicken-stir-fry', 2, 'broccoli', 200, 'g', false),
  ('chicken-stir-fry', 3, 'soy sauce', 3, 'tbsp', false),
  ('chicken-stir-fry', 4, 'garlic', 2, 'pcs', false),
  ('chicken-stir-fry', 5, 'rice', 250, 'g', false),
  ('tomato-soup', 0, 'tomato', 8, 'pcs', false),
  ('tomato-soup', 1, 'onion', 1, 'pcs', false),
  ('tomato-soup', 2, 'garlic', 3, 'pcs', false),
  ('tomato-soup', 3, 'olive oil', 2, 'tbsp', false),
  ('tomato-soup', 4, 'vegetable broth', 500, 'ml', false),
  ('guacamole', 0, 'avocado', 3, 'pcs', false),
  ('guacamole', 1, 'lime', 1, 'pcs', false),
  ('guacamole', 2, 'onion', 0.5, 'pcs', false),
  ('guacamole', 3, 'tomato', 1, 'pcs', false),
  ('guacamole', 4, 'cilantro', 2, 'tbsp', true),
  ('fried-rice', 0, 'rice', 300, 'g', false),
  ('fried-rice', 1, 'egg', 2, 'pcs', false),
  ('fried-rice', 2, 'soy sauce', 2, 'tbsp', false),
  ('fried-rice', 3, 'green onion', 2, 'pcs', false),
  ('fried-rice', 4, 'peas', 100, 'g', true),
  ('banana-bread', 0, 'banana', 3, 'pcs', false),
  ('banana-bread', 1, 'flour', 250, 'g', false),
  ('banana-bread', 2, 'sugar', 150, 'g', false),
  ('banana-bread', 3, 'butter', 100, 'g', false),
  ('banana-bread', 4, 'egg', 1, 'pcs', false),
  ('banana-bread', 5, 'baking soda', 1, 'tsp', false);
